name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - humble
  pull_request:
    branches:
      - humble

jobs:
  industrial_ci:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        ROS_DISTRO: [humble]
        ROS_REPO: [testing, main]
    env:
      ROS_DISTRO: ${{ matrix.ROS_DISTRO }}
      ROS_REPO: ${{ matrix.ROS_REPO }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1
      - name: Source tests
        uses: "ros-industrial/industrial_ci@master"
        env:
          DOWNSTREAM_WORKSPACE: "github:LeoRover/leo_robot-ros2#humble github:LeoRover/leo_desktop-ros2#humble"

  ament_lint:
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-20.04
    container:
      image: ubuntu:jammy
    strategy:
      fail-fast: false
      matrix:
        linter: [lint_cmake, xmllint]
    steps:
      - uses: actions/checkout@v3
      - uses: ros-tooling/setup-ros@v0.3
        with:
          required-ros-distributions: humble
      - uses: ros-tooling/action-ros-lint@v0.1
        with:
          distribution: humble
          linter: ${{ matrix.linter }}
          package-name: |
            leo
            leo_description
            leo_msgs
            leo_teleop
